@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes addApptCommand;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Patient with NRIC found])
    if () then ([No duplicate appointment present])
        :Add Appointment to
        AppointmentList in AddressBook;
    else ([Duplicate found])
        :CommandException;
    endif
else ([NRIC not found]))
    : CommandException;
endif
stop
@enduml
