@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successful])
    :Save new contact to
    addressbook;
else ([command unsuccessful])
    :Error messages;
    :Edit command
    accordingly;
    :Successfully saves
    new contact;
endif
stop
@enduml
