@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant ":ArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR
participant "multi:ArgumentMultimap" as ArgumentMultimap LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
end box

mainFrame sd parse fields
AddCommandParser -> ParserUtil : parseName(...)
activate ParserUtil
ParserUtil --> AddCommandParser
deactivate ParserUtil
AddCommandParser -> ParserUtil : parsePhone(...)
activate ParserUtil
ParserUtil --> AddCommandParser
deactivate ParserUtil
AddCommandParser -> ParserUtil : parseEmail(...)
activate ParserUtil
ParserUtil --> AddCommandParser
deactivate ParserUtil
AddCommandParser -> ParserUtil : parseAddress(...)
activate ParserUtil
ParserUtil --> AddCommandParser
deactivate ParserUtil
AddCommandParser -> ParserUtil : parseTags(...)
activate ParserUtil
ParserUtil --> AddCommandParser
deactivate ParserUtil

' Callback
AddCommandParser -> AddCommandParser : handleOptionalMatric(...)
activate AddCommandParser
AddCommandParser --> AddCommandParser
deactivate AddCommandParser
AddCommandParser -> AddCommandParser : handleOptionalReflection(...)
activate AddCommandParser
AddCommandParser --> AddCommandParser
deactivate AddCommandParser
AddCommandParser -> AddCommandParser : handleOptionalStudio(...)
activate AddCommandParser
AddCommandParser --> AddCommandParser
deactivate AddCommandParser
@enduml
