@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:Add/Edit CommandParser parses arguments;
:ArgumentTokenizer tokenizes attributes;
if () then ([has certain duplicated prefixes])
    :Display duplicate prefix error;
    stop
else
    :Parse attributes into classes;
    if () then ([has attribute parsing error])
        :Display attribute parsing error;
        stop
    else ()
        :Create Person instance with supplied attributes;
        :Create Add/Edit Command instance with Person instance;
        :Execute Add/Edit Command instance;
        if () then ([person already exists in FitBook])
            :Display duplicate person error;
            stop
        else ()
            :Add person to FitBook;
            :Save persons to JSON file;
            :Display successful add/edit command result;
            stop
        endif
    endif
endif
@enduml
