@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes addnote command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successful])
    :Add new note to
    specified patient;
else ([command unsuccessful])
    :Error messages;
    :Edit command
    accordingly;
    :Successfully adds
    new note;
endif
stop
@enduml
