@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddNoteCommandParser" as AddNoteCommandParser LOGIC_COLOR
participant "n:AddNoteCommand" as AddNoteCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addnote \n i/T0123456A n/Covid")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("addnote \n i/T0123456A n/Covid")
activate AddressBookParser

create AddNoteCommandParser
AddressBookParser -> AddNoteCommandParser
activate AddNoteCommandParser

AddNoteCommandParser --> AddressBookParser
deactivate AddNoteCommandParser

AddressBookParser -> AddNoteCommandParser : parse("i/T0123456A n/Covid")
activate AddNoteCommandParser

create AddNoteCommand
AddNoteCommandParser -> AddNoteCommand
activate AddNoteCommand

AddNoteCommand --> AddNoteCommandParser :
deactivate AddNoteCommand

AddNoteCommandParser --> AddressBookParser : n
deactivate AddNoteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddNoteCommandParser -[hidden]-> AddressBookParser
destroy AddNoteCommandParser

AddressBookParser --> LogicManager : n
deactivate AddressBookParser

LogicManager -> AddNoteCommand : execute(m)
activate AddNoteCommand

AddNoteCommand -> Model : setPerson(T0123456A, \n new Person(..., Covid, ...))
activate Model

Model --> AddNoteCommand
deactivate Model

create CommandResult
AddNoteCommand -> CommandResult
activate CommandResult

CommandResult --> AddNoteCommand
deactivate CommandResult

AddNoteCommand --> LogicManager : r
deactivate AddNoteCommand

[<--LogicManager
deactivate LogicManager
@enduml
