@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddOrderCommandParser" as AddOrderCommandParser LOGIC_COLOR
participant "a:AddOrderCommand" as AddOrderCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Order ORDER_COLOR_T1
participant ":Order" as Order ORDER_COLOR
end box

box Person PERSON_COLOR_T1
participant "p:Person" as Person PERSON_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(args)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(args)
activate AddressBookParser

create AddOrderCommandParser
AddressBookParser -> AddOrderCommandParser
activate AddOrderCommandParser

create Order
AddOrderCommandParser -> Order : new Order(orderArgs)
activate Order

Order --> AddOrderCommandParser : order
deactivate Order

AddOrderCommandParser --> AddressBookParser
deactivate AddOrderCommandParser

AddressBookParser -> AddOrderCommandParser : parse(args)
activate AddOrderCommandParser

create AddOrderCommand
AddOrderCommandParser -> AddOrderCommand
activate AddOrderCommand

AddOrderCommand --> AddOrderCommandParser :
deactivate AddOrderCommand

AddOrderCommandParser --> AddressBookParser : a
deactivate AddOrderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddOrderCommandParser -[hidden]-> AddressBookParser
destroy AddOrderCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddOrderCommand : execute(m)
activate AddOrderCommand

AddOrderCommand --> Person : addOrder(order)
activate Person

Person --> AddOrderCommand :
deactivate Person

AddOrderCommand --> Model : setPerson(p)
activate Model

Model --> AddOrderCommand :
deactivate Model

create CommandResult
AddOrderCommand -> CommandResult
activate CommandResult

CommandResult --> AddOrderCommand
deactivate CommandResult

AddOrderCommand --> LogicManager : r
deactivate AddOrderCommand

[<--LogicManager : r
deactivate LogicManager
@enduml
