@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes "task" command;
:New task is created and
added to TaskMasterPro;
:Save after execution
completes;
stop
@enduml
