@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Person MODEL_COLOR_T1
participant ":Person" as Person MODEL_COLOR
participant ":Analytics" as Analytics MODEL_COLOR
end box

[-> Person : getAnalytics()
activate Person

Person -> Analytics : getAnalytics(LoanRecords)
activate Analytics

loop LoanRecords.size() times
Analytics -> Analytics :updateNumFields(Loan)
Analytics -> Analytics :updateValueFields(Loan)
Analytics -> Analytics :updateDateFields(Loan)
end
Analytics -> Analytics :updatePropFields(Loan)
Analytics -> Analytics :updateAverageFields(Loan)
Analytics --> Person :
deactivate Analytics

[<-- Person
deactivate Person

@enduml
