@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class UI UI_COLOR
    Class InternshipLogic LOGIC_COLOR
    Class Storage STORAGE_COLOR
    Class InternshipModel MODEL_COLOR
    Class Main #grey
    Class Commons LOGIC_COLOR_T2
}

Class "<$user>" as User MODEL_COLOR_T2
Class "<$documents>" as File UI_COLOR_T1


UI -[#green]> InternshipLogic
UI -right[#green]-> InternshipModel
InternshipLogic -[#blue]-> Storage
InternshipLogic -down[#blue]-> InternshipModel
Main -[#grey]-> UI
Main -[#grey]-> InternshipLogic
Main -[#grey]-> Storage
Main -up[#grey]-> InternshipModel
Main -down[hidden]-> Commons

Storage -up[STORAGE_COLOR].> InternshipModel
Storage .right[STORAGE_COLOR].>File
User ..> UI
@enduml
