@startuml
'https://plantuml.com/object-diagram

Package Model as ModelPackage <<Rectangle>>{
object "<u>:TaskMasterPro" as TaskMasterPro
object "<u>:TaskList" as TaskList

TaskMasterPro - TaskList

object "<u>:UniqueEmployeeList" as UniqueEmployeeList
TaskMasterPro - UniqueEmployeeList
}

@enduml
