@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueEmployeeList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueEmployeeList
UniqueTagList -[hidden]down- UniqueEmployeeList

UniqueTagList -right-> "*" Tag
UniqueEmployeeList -right-> Employee

Employee -up-> "*" Tag

Employee *--> Name
Employee *--> Phone
Employee *--> Email
Employee *--> Address
@enduml
