@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueGroupList
UniqueGroupList -[hidden]down- UniquePersonList
UniqueGroupList -[hidden]down- UniquePersonList

UniqueGroupList -right-> "*" Group
UniquePersonList -right-> Person

Person -up-> "*" Group

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Major
Person *--> Year
Person *--> Telegram
Person *--> "0..1" Remark
@enduml
