@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits TaskMasterPro])
    :Purge redundant states;
    :Save TaskMasterPro to
    taskMasterProStateList;
else ([else])
endif
stop
@enduml
