@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters command;

if () then ([Decline confirmation])
    stop
else ([Accept confirmation])

if () then ([command commits AddressBook])
    :Purge redundant states;
    :Save AddressBook to
    addressBookStateList;
else ([else])
endif
stop
@enduml
