@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {
Class "<<interface>>\nInternshipLogic" as Logic
Class InternshipLogicManager
}

package Model as ModelPackage {
Class "<<interface>>\nInternshipModel" as Model
Class InternshipModelManager
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

InternshipLogicManager .up.|> Logic
InternshipModelManager .up.|> Model
StorageManager .up.|> Storage

InternshipLogicManager --> Model
InternshipLogicManager --> Storage
@enduml
