@startuml
!include style.puml
skinparam ArrowFontStyle plain

participant ":CourseMateListClickHandler" as CourseMateListClickHandler UI_COLOR
participant ":MultipleSelectionModel<CourseMate>" as MultipleSelectionModel UI_COLOR
participant "mainWindow:CourseMateListSelectHandler" as CourseMateListSelectHandler UI_COLOR
participant ":CourseMateDetailPanel" as CourseMateDetailPanel UI_COLOR
participant ":Logic" as Logic LOGIC_COLOR

[-> CourseMateListClickHandler : handle(event)
activate CourseMateListClickHandler

CourseMateListClickHandler -> MultipleSelectionModel : getSelectedItem()
activate MultipleSelectionModel

MultipleSelectionModel --> CourseMateListClickHandler: courseMate
deactivate MultipleSelectionModel

CourseMateListClickHandler -> CourseMateListSelectHandler : handleCourseMateListSelect(courseMate)
activate CourseMateListSelectHandler

CourseMateListSelectHandler -> Logic: setRecentlyProcessedCourseMate(courseMate)
activate Logic

Logic --> CourseMateListSelectHandler
deactivate Logic

CourseMateListSelectHandler -> CourseMateDetailPanel: loadCourseMate(courseMate)
activate CourseMateDetailPanel

CourseMateDetailPanel --> CourseMateListSelectHandler
deactivate CourseMateDetailPanel

[<--CourseMateListClickHandler
deactivate CourseMateListClickHandler
@enduml
