@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteEventCommandParser" as DeleteEventCommandParser LOGIC_COLOR
participant "a:DeleteEventCommand" as DeleteEventCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1 e/ 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1 e/ 1")
activate AddressBookParser

create DeleteEventCommandParser
AddressBookParser -> DeleteEventCommandParser
activate DeleteEventCommandParser

DeleteEventCommandParser --> AddressBookParser
deactivate DeleteEventCommandParser

AddressBookParser -> DeleteEventCommandParser : parse("delete 1 e/ 1")
activate DeleteEventCommandParser

Create DeleteEventCommand
DeleteEventCommandParser -> DeleteEventCommand
activate DeleteEventCommand

DeleteEventCommand --> DeleteEventCommandParser : a
deactivate DeleteEventCommand

DeleteEventCommandParser --> AddressBookParser : a
deactivate DeleteEventCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.'
DeleteEventCommandParser -[hidden]-> AddressBookParser
destroy DeleteEventCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> DeleteEventCommand : execute()
activate DeleteEventCommand

DeleteEventCommand -> Model : setPatient(args)
activate Model

Model --> DeleteEventCommand
deactivate Model

DeleteEventCommand -> Model : updateFilteredPatientList(p)
activate Model

Model -> DeleteEventCommand
deactivate Model

create CommandResult
DeleteEventCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteEventCommand
deactivate CommandResult

DeleteEventCommand --> LogicManager : result
deactivate DeleteEventCommand

DeleteEventCommand -[hidden]-> AddressBookParser
destroy DeleteEventCommand

[<--LogicManager
deactivate LogicManager

@enduml
