@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:DeleteCommandParser parses arguments;
:ParseIndex gets index from parsed arguments;
if () then ([Valid])
    :Create DeleteCommand instance with supplied index;
    :Execute DeleteCommand instance;
    :Delete person from FitBook;
    :Display success message;
    stop
else ([Invalid index])
    :Display invalid index error;
    stop
endif
@enduml
