@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes edit command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successful])
    :Update patient's
    information;
else ([command unsuccessful])
    :Error messages;
    :Edit command
    accordingly;
    :Successfully update
    patient's information;
endif
    :Saves and displays
    updated information;
stop
@enduml
