@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "e:ExportCommand" as ExportCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
participant "a:AddressBook" as AddressBook MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant "j:JsonAddressBookStorage" as JsonAddressBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("export")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("export")
activate AddressBookParser

create ExportCommand
AddressBookParser -> ExportCommand : new ExportCommand()
activate ExportCommand

ExportCommand --> AddressBookParser : e
deactivate ExportCommand

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> ExportCommand : execute(m)
activate ExportCommand

ExportCommand -> Model : getFilteredPersonList()
activate Model

Model --> ExportCommand : l
deactivate Model

create AddressBook
ExportCommand -> AddressBook : new AddressBook()
activate AddressBook

AddressBook --> ExportCommand : a
deactivate AddressBook

ExportCommand -> ExportCommand : addToAddressBook(a, l);
activate ExportCommand

loop for each person in l

    ExportCommand -> AddressBook : addPerson(person)
    activate AddressBook

    AddressBook --> ExportCommand
    deactivate AddressBook

end

ExportCommand --> ExportCommand
deactivate ExportCommand

create JsonAddressBookStorage
ExportCommand -> JsonAddressBookStorage : new JsonAddressBookStorage();
activate JsonAddressBookStorage

JsonAddressBookStorage --> ExportCommand : j
deactivate JsonAddressBookStorage

ExportCommand -> ExportCommand : writeToJsonFile(j, a);
activate ExportCommand

ExportCommand -> JsonAddressBookStorage : saveAddressBook(a)
activate JsonAddressBookStorage

JsonAddressBookStorage --> ExportCommand
deactivate JsonAddressBookStorage

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> ExportCommand : readJsonFile(jsonFile)
activate ExportCommand

ExportCommand --> ExportCommand : jsonTree
deactivate ExportCommand

ExportCommand -> ExportCommand : readPersonsArray(jsonTree)
activate ExportCommand

ExportCommand --> ExportCommand : readPersonsArray
deactivate ExportCommand

ExportCommand -> ExportCommand : createCsvDirectory(csvFile)
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

ExportCommand -> ExportCommand : writeToCsvFile(csvFile, personsArray)
activate ExportCommand

ExportCommand --> ExportCommand
deactivate ExportCommand

create CommandResult
ExportCommand -> CommandResult
activate CommandResult

CommandResult --> ExportCommand
deactivate CommandResult

ExportCommand --> LogicManager : r
deactivate ExportCommand

[<--LogicManager
deactivate LogicManager
@enduml
