@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes filter command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([criteria is given])
    if () then ([Person fulfils criteria])
        :Show in list;
    else ([else])
        :Not shown in list;
    endif
else ([else])
    :Show error message to User;
endif
stop
@enduml
