@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "e:FilterCommand" as FilterCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter /role SWE /stage initial_application")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("filter /role SWE /stage initial_application")
activate AddressBookParser

create FilterCommandParser
AddressBookParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> AddressBookParser
deactivate FilterCommandParser

AddressBookParser -> FilterCommandParser : parse("/role SWE /stage initial_application")
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand :
activate FilterCommand

FilterCommand --> FilterCommandParser
deactivate FilterCommand

FilterCommandParser --> AddressBookParser : e
deactivate FilterCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> AddressBookParser
destroy FilterCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> FilterCommand : execute(m)
activate FilterCommand

FilterCommand -> Model : updateFilteredPersonList(matchesCriteria)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand :
deactivate CommandResult

FilterCommand --> LogicManager : r
deactivate FilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
