@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

:User executes command;
if () then ([invalid arguments])
  :Alert user of error;
    else ([valid arguments])
      while () is ([more appointments to filter])
        :Process next appointment;
        if () then ([pass check])
          :Add appointment to list;
        else ([no])
        endif
        endwhile ([all checked])
      :Return filtered list of appointments;
      :Display list;
      :User gets feedback;
    endif
    stop
@enduml
