@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute( "list" )
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("list")
activate AddressBookParser

Create ListCommand
AddressBookParser -> ListCommand
activate ListCommand

ListCommand --> AddressBookParser : a
deactivate ListCommand

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : updateFilteredPatientList(p)
activate Model

Model --> ListCommand
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand :
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

ListCommand -[hidden]-> AddressBookParser
destroy ListCommand

[<--LogicManager
deactivate LogicManager

@enduml
