@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

Class AddressBookParser

Class CommandType
Class XYZCommand
Class "{abstract}\nCommand" as Command


Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

Logic .[hidden]down.> AddressBookParser

LogicManager .left.|> Logic
LogicManager -->"1" AddressBookParser

AddressBookParser ..> CommandType : uses >

CommandType .right.> XYZCommand : creates >

XYZCommand -up-|> Command
LogicManager ..> Command : executes >

LogicManager --> Model
LogicManager -right-> Storage

Storage --[hidden] Model

Command .[hidden]up.> Storage
Command .right.> Model
note right of XYZCommand: XYZCommand = AddCommand, \nFindCommand, etc

@enduml
