@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskMasterProParser" as TaskMasterProParser LOGIC_COLOR
participant ":MarkCommandParser" as MarkCommandParser LOGIC_COLOR
participant "a:MarkCommand" as MarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mark 1")
activate LogicManager

LogicManager -> TaskMasterProParser : parseCommand("mark 1")
activate TaskMasterProParser

create MarkCommandParser
TaskMasterProParser -> MarkCommandParser
activate MarkCommandParser

MarkCommandParser --> TaskMasterProParser
deactivate MarkCommandParser

TaskMasterProParser -> MarkCommandParser : parse(" 1")
activate MarkCommandParser

create MarkCommand
MarkCommandParser -> MarkCommand
activate MarkCommand

MarkCommand --> MarkCommandParser :
deactivate MarkCommand

MarkCommandParser --> TaskMasterProParser : a
deactivate MarkCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkCommandParser -[hidden]-> TaskMasterProParser
destroy MarkCommandParser

TaskMasterProParser --> LogicManager : a
deactivate TaskMasterProParser

LogicManager -> MarkCommand : execute(m)
activate MarkCommand

'Put this into a ref block'

group ref [update existing Employee fields]
MarkCommand -[hidden]-> Model
end

'Up to here is inside the ref block'

create CommandResult
MarkCommand -> CommandResult
activate CommandResult

CommandResult --> MarkCommand
deactivate CommandResult

MarkCommand --> LogicManager : r
deactivate MarkCommand

[<--LogicManager
deactivate LogicManager
@enduml
