@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MarkCommandParser" as MarkCommandParser LOGIC_COLOR
participant "p:MarkCommand" as MarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("mark 1 /t Assignment1 /ts cg")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("mark 1 /t Assignment1 /ts cg")
activate AddressBookParser

create MarkCommandParser
AddressBookParser -> MarkCommandParser
activate MarkCommandParser

MarkCommandParser --> AddressBookParser
deactivate MarkCommandParser

AddressBookParser -> MarkCommandParser : parse("1 /t Assignment1 /ts cg")
activate MarkCommandParser

create MarkCommand
MarkCommandParser -> MarkCommand
activate MarkCommand

MarkCommand --> MarkCommandParser :
deactivate MarkCommand

MarkCommandParser --> AddressBookParser : p
deactivate MarkCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
MarkCommandParser -[hidden]-> AddressBookParser
destroy MarkCommandParser

AddressBookParser --> LogicManager : p
deactivate AddressBookParser

LogicManager -> MarkCommand : execute(m)
activate MarkCommand

MarkCommand -> Model : setPerson(personToEdit, editedPerson)
activate Model

Model --> MarkCommand
deactivate Model

create CommandResult
MarkCommand -> CommandResult
activate CommandResult

CommandResult --> MarkCommand
deactivate CommandResult

MarkCommand --> LogicManager : r
deactivate MarkCommand

[<--LogicManager
deactivate LogicManager
@enduml
