@startuml
!include style.puml
skinparam {
    arrowThickness 1.1
    arrowColor MODEL_COLOR
    classBackgroundColor MODEL_COLOR
    classBorderColor MODEL_COLOR
    ClassStereotypeFontColor MODEL_COLOR
    classBorderColor<<hide>> #FFFFFF
    ClassStereotypeFontColor<<hide>> #FFFFFF
}

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueBookingList
Class UniquePersonList
together{
    Class "FilteredList <Person>" as FilteredListPerson
    Class "FilteredList <Booking>" as FilteredListBooking
}
note "Used by UI component for display to user" as N1
FilteredListPerson .right. N1
FilteredListBooking .. N1

Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Booking
Class Description
Class StartTime
Class EndTime

}

Class HiddenOutside <<hide>> #FFFFFF
HiddenOutside ..> Model

Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook

ModelManager .up.|> Model
AddressBook .up.|> ReadOnlyAddressBook
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs

ModelManager --> "1" FilteredListPerson
ModelManager --> "1" FilteredListBooking

AddressBook *--> "1" UniquePersonList
AddressBook *--> "1" UniqueBookingList

UniqueBookingList --> "~*" Booking
UniquePersonList --> "~*" Person
Person *--> "1" Name
Person *--> "0..1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
Person *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email
Email -[hidden]right-> Tag

Booking *-->"1" Description
Booking *--> "1" StartTime
Booking *--> "1" EndTime

@enduml
