@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyInternshipData" as ReadOnlyInternshipData
Class "<<interface>>\nReadOnlyInternshipUserPrefs" as ReadOnlyInternshipUserPrefs
Class "<<interface>>\nInternshipModel" as InternshipModel
Class InternshipData
Class InternshipModelManager
Class InternshipUserPrefs

Class UniqueInternshipList
Class Internship
Class ApplicationStatus
Class CompanyName
Class ContactName
Class ContactNumber
Class ContactEmail
Class Description
Class Location
Class Role

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> InternshipModel

InternshipData .up.|> ReadOnlyInternshipData

InternshipModelManager .up.|> InternshipModel
InternshipModel .right.> ReadOnlyInternshipUserPrefs
InternshipModel .left.> ReadOnlyInternshipData
InternshipModelManager -left-> "1" InternshipData
InternshipModelManager -right-> "1" InternshipUserPrefs
InternshipUserPrefs .up.|> ReadOnlyInternshipUserPrefs

InternshipData *--> "1" UniqueInternshipList
InternshipModelManager --> "~* filtered" Internship
UniqueInternshipList --> "~* all" Internship
Internship *--> ApplicationStatus
Internship *--> CompanyName
Internship *--> ContactName
Internship *--> ContactNumber
Internship *--> ContactEmail
Internship *--> Description
Internship *--> Location
Internship *--> Role

Internship -[hidden]up--> I
UniqueInternshipList -[hidden]right-> I

CompanyName -[hidden]right-> ContactNumber
ContactNumber -[hidden]right-> Description
Description -[hidden]right-> Role


@enduml
