@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand
Class FindAndExportCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class XYZCommandParser
Class FindAndExportCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser: <<create>>
AddressBookParser .down.> FindAndExportCommandParser: <<create>>

XYZCommandParser ..> XYZCommand : <<create>>
FindAndExportCommandParser ..> FindAndExportCommand : <<create>>
AddressBookParser ..> Command : <<use>>
XYZCommandParser .up.|> Parser
FindAndExportCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
FindAndExportCommandParser ..> ArgumentMultimap
FindAndExportCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
FindAndExportCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
FindAndExportCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
FindAndExportCommand -up-|> Command

note right of XYZCommandParser: XYZCommandParser = AddCommandParser, AddressBookParser,\nDeleteCommandParser, EditCommandParser,\nFindAndExportCommandParser, ImportCommandParser

note bottom of XYZCommand: See XYZCommand subclasses in\nLogicClassDiagram.puml

@enduml
