@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Ui UI_COLOR_T1
participant ":PaymentWindow" as PaymentWindow UI_COLOR
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "command:ResetDebtCommand" as ResetDebtCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> PaymentWindow : button click
activate PaymentWindow

PaymentWindow -> MainWindow : onResetDebt()
activate MainWindow

create ResetDebtCommand
MainWindow -> ResetDebtCommand
activate ResetDebtCommand

ResetDebtCommand -> MainWindow
deactivate ResetDebtCommand

MainWindow -> MainWindow : execute(command)
activate MainWindow

MainWindow -> LogicManager : execute(command)
activate LogicManager

LogicManager -> ResetDebtCommand : execute(command)
activate ResetDebtCommand

ResetDebtCommand -> Model : resetDebt(person)
activate Model

Model --> ResetDebtCommand
deactivate Model

create CommandResult
ResetDebtCommand -> CommandResult
activate CommandResult

CommandResult --> ResetDebtCommand
deactivate CommandResult

ResetDebtCommand --> LogicManager : r
deactivate ResetDebtCommand

LogicManager --> MainWindow : r
deactivate LogicManager

MainWindow --> MainWindow
deactivate MainWindow

MainWindow --> PaymentWindow
deactivate MainWindow

[<--PaymentWindow
deactivate PaymentWindow
@enduml
