@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User requests to
execute command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command will modify persons])
    :Remove all states
    from redoStack;
    :Save persons to
    undoStack;
else ([else])
endif

:Execute command;

stop
@enduml
