@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User starts NetConnect;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.


if () then ([else])
    :Create New StateStorage file;
else ([StateStorage exists])
endif
:Load last command from StateStorage file;
:Display last command to user;

while () is ([User changes command input])
    :Save command string to StateStorage file;
endwhile ([else])
stop
@enduml
