@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":SearchStudentCommandParser" as SearchStudentCommandParser LOGIC_COLOR
participant "p:NameContainsKeywordPredicate" as NameContainsKeywordPredicate LOGIC_COLOR
participant "s:SearchStudentCommand" as SearchStudentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("/search_student name/Bob")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("/search_student name/Bob")
activate AddressBookParser

create SearchStudentCommandParser
AddressBookParser -> SearchStudentCommandParser
activate SearchStudentCommandParser

SearchStudentCommandParser --> AddressBookParser
deactivate SearchStudentCommandParser

AddressBookParser -> SearchStudentCommandParser : parse("name/Bob")
activate SearchStudentCommandParser

create NameContainsKeywordPredicate
SearchStudentCommandParser -> NameContainsKeywordPredicate
activate NameContainsKeywordPredicate

NameContainsKeywordPredicate --> SearchStudentCommandParser
deactivate NameContainsKeywordPredicate

create SearchStudentCommand
SearchStudentCommandParser -> SearchStudentCommand
activate SearchStudentCommand

SearchStudentCommand --> SearchStudentCommandParser :
deactivate SearchStudentCommand

SearchStudentCommandParser --> AddressBookParser : s
deactivate SearchStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SearchStudentCommandParser -[hidden]-> AddressBookParser
destroy SearchStudentCommandParser

AddressBookParser --> LogicManager : s
deactivate AddressBookParser

LogicManager -> SearchStudentCommand : execute(m)
activate SearchStudentCommand

SearchStudentCommand -> Model : updateFilteredPersonList(p)
activate Model

Model --> SearchStudentCommand
deactivate Model

create CommandResult
SearchStudentCommand -> CommandResult
activate CommandResult

CommandResult --> SearchStudentCommand
deactivate CommandResult

SearchStudentCommand --> LogicManager : r
deactivate SearchStudentCommand

[<--LogicManager
deactivate LogicManager

@enduml
