@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes show command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command successful])
    :Displays contact in
    side window;
else ([command unsuccessful])
    :Error messages;
    :Edit command
    accordingly;
    :Successfully displays
    contact in side window;
endif
stop
@enduml
