@startuml
!pragma useVerticalIf on
start
:User enters star command;
if () then ([else])
  :Error:Invalid command format;
  stop
( [Student index and number of stars to award provided]) elseif () then ([else])
  :Error: Invalid Student index;
  stop
else ( [Student index is in valid range of Student List])
endif
  :Star Command successfully executes.
Student is awarded the number of stars.;
stop

@enduml
