@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ContactList Storage" #F4F6F6{
Class "<<interface>>\nContactListStorage" as ContactListStorage
Class JsonContactListStorage
Class JsonSerializableContactList
Class JsonAdaptedCourseMate
Class JsonAdaptedSkill
}

package "GroupList Storage" #F4F6F6{
Class "<<interface>>\nGroupListStorage" as GroupListStorage
Class JsonGroupListStorage
Class JsonSerializableGroupList
Class JsonAdaptedGroup
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .right.|> Storage
StorageManager --> "1" UserPrefsStorage
StorageManager --> "1" ContactListStorage
StorageManager --> "1" GroupListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ContactListStorage
Storage -right-|> GroupListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonContactListStorage .up.|> ContactListStorage
JsonGroupListStorage .up.|> GroupListStorage

JsonContactListStorage ..> JsonSerializableContactList
JsonSerializableContactList --> "*" JsonAdaptedCourseMate
JsonAdaptedCourseMate --> "*" JsonAdaptedSkill

JsonGroupListStorage ..> JsonSerializableGroupList
JsonSerializableGroupList --> "*" JsonAdaptedGroup
JsonAdaptedGroup --> "*" JsonAdaptedCourseMate

@enduml
