@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ContactList Storage" #F4F6F6{
Class "<<interface>>\nContactListStorage" as ContactListStorage
Class JsonContactListStorage
Class JsonSerializableContactList
Class JsonAdaptedCourseMate
Class JsonAdaptedSkill
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ContactListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ContactListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonContactListStorage .up.|> ContactListStorage
JsonContactListStorage ..> JsonSerializableContactList
JsonSerializableContactList --> "*" JsonAdaptedCourseMate
JsonAdaptedCourseMate --> "*" JsonAdaptedSkill

@enduml
