@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

rectangle AddressBook {
    class "undoStack\n----" as undoStack
    class "persons list\n----\nState 0" as persons
    class "redoStack\n----" as redoStack
}
undoStack -[hidden]right- persons
persons -[hidden]right- redoStack
@end
