@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StaffConnectParser" as StaffConnectParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> StaffConnectParser : parseCommand(undo)
activate StaffConnectParser

create UndoCommand
StaffConnectParser -> UndoCommand
activate UndoCommand

UndoCommand --> StaffConnectParser
deactivate UndoCommand

StaffConnectParser --> LogicManager : u
deactivate StaffConnectParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoStaffBook()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
