@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant "persons:UniquePersonList" as persons MODEL_COLOR
end box

[-> Model : undo()
activate Model

Model -> AddressBook : undo()
activate AddressBook

AddressBook -> AddressBook :savePersonsTo(redoStack)

AddressBook -> persons : setPersons(personFromUndoStack)
activate persons
persons --> AddressBook
deactivate persons

AddressBook --> Model :
deactivate AddressBook

[<-- Model
deactivate Model

@enduml
