@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MatchMateParser" as MatchMateParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> MatchMateParser : parseCommand(undo)
activate MatchMateParser

create UndoCommand
MatchMateParser -> UndoCommand
activate UndoCommand

UndoCommand --> MatchMateParser
deactivate UndoCommand

MatchMateParser --> LogicManager : u
deactivate MatchMateParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoContactList()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
