@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TaskMasterProParser" as TaskMasterProParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> TaskMasterProParser : parseCommand(undo)
activate TaskMasterProParser

create UndoCommand
TaskMasterProParser -> UndoCommand
activate UndoCommand

UndoCommand --> TaskMasterProParser
deactivate UndoCommand

TaskMasterProParser --> LogicManager : u
deactivate TaskMasterProParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoTaskMasterPro()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
