@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "add n/David..."

rectangle AddressBook {
    class "undoStack\n----\nState 1\nState 0" as undoStack
    class "persons list\n----\nState 2" as persons
    class "redoStack\n----" as redoStack
}
undoStack -[hidden]right- persons
persons -[hidden]right- redoStack
@end
