@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTaskMasterPro" as VersionedTaskMasterPro MODEL_COLOR
end box

[-> Model : undoTaskMasterPro()
activate Model

Model -> VersionedTaskMasterPro : undo()
activate VersionedTaskMasterPro

VersionedTaskMasterPro -> VersionedTaskMasterPro :resetData(ReadOnlyTaskMasterPro)
VersionedTaskMasterPro --> Model :
deactivate VersionedTaskMasterPro

[<-- Model
deactivate Model

@enduml
