package seedu.address.logic.parser;

import static seedu.address.logic.Messages.MESSAGE_INVALID_COMMAND_FORMAT;
import static seedu.address.logic.parser.CliSyntax.PREFIX_ADDRESS;
import static seedu.address.logic.parser.CliSyntax.PREFIX_EMAIL;
import static seedu.address.logic.parser.CliSyntax.PREFIX_NAME;
import static seedu.address.logic.parser.CliSyntax.PREFIX_PHONE;
import static seedu.address.logic.parser.CliSyntax.PREFIX_TAG;

import java.util.HashMap;
import java.util.Set;
import java.util.stream.Stream;

import seedu.address.logic.commands.AddCommand;
import seedu.address.logic.parser.exceptions.ParseException;
import seedu.address.model.person.Address;
import seedu.address.model.person.Email;
import seedu.address.model.person.Name;
import seedu.address.model.person.Person;
import seedu.address.model.person.Phone;
import seedu.address.model.tag.Tag;

/**
 * Parses input arguments and creates a new AddCommand object
 */
public class AddCommandParser implements Parser<AddCommand> {

    /**
     *  Parses the given {@code String} of arguments in the context of the AddCommand
     *  and returns an AddCommand object for execution.
     *  Command format: add /attibuteName1 attributeValue1 /attributeName2 attributeValue2 ...
     *  Examples:
     *  add
     *  add /Name Alice /Phone 123456 /address 123 ABC Street
     */
    public AddCommand parse(String args) throws ParseException {
        args = args.replaceFirst("add", "").trim();
        if (args.isEmpty()) {
            return new AddCommand(new HashMap<>());
        } else {
            String[] parts = args.split("/", -1);
            parts = removeFirstEmptyString(parts);
            requireValidParts(parts);
            HashMap<String, String> attributeMap = getAttributeHashMapFromAttributeStrings(parts);
            return new AddCommand(attributeMap);
        }

    }

    private String[] removeFirstEmptyString(String[] parts) {
        // Solution below generated by GitHub Copilot
        if (parts[0].isEmpty()) {
            String[] newParts = new String[parts.length - 1];
            System.arraycopy(parts, 1, newParts, 0, parts.length - 1);
            return newParts;
        }
        return parts;
    }

    private static HashMap<String, String> getAttributeHashMapFromAttributeStrings(String[] parts) {
        HashMap<String, String> attributeMap = new HashMap<>();
        for (int i = 0; i < parts.length; i++) {
            String[] attribute = separateAttributeNamesAndValues(parts[i]);
            String attributeName = attribute[0];
            String attributeValue = attribute[1];
            attributeMap.put(attributeName, attributeValue);
        }
        return attributeMap;
    }

    private void requireValidParts(String[] parts) throws ParseException {
        for (int i = 0; i < parts.length; i++) {
            if (separateAttributeNamesAndValues(parts[i]).length != 2) {
                throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, AddCommand.MESSAGE_USAGE));
            }
        }
    }

    private static String[] separateAttributeNamesAndValues(String parts) {
        return parts.trim().split(" ", 2);
    }

    /**
     * Returns true if none of the prefixes contains empty {@code Optional} values in the given
     * {@code ArgumentMultimap}.
     */
    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
        return Stream.of(prefixes).allMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
    }

}
