@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class NoteCommandParser {
  +parse(): NoteCommand
}
Class ParserException

NoteCommandParser .up.|> Parser
Parser .right.> ParserException: throws >
NoteCommandParser .right.> ParserException: throws >
@enduml
