#!/bin/sh
# @@author rertyy-reused
# Reused from https://imnnquy.medium.com/development-team-setup-pre-commit-hook-and-check-commit-message-dd37313196e7

set -e

# Check style for main and test
./gradlew checkstyleMain
./gradlew checkstyleTest
./gradlew test

# Check the exit status from gradle command
if [ $? -eq 0 ]; then
  echo "Your code has been validated successfully!"
else
  echo "Validation failed, please check your code and try again..."
  exit 1
fi
# @@author
